# Archivo de configuración de Alacritty

# Otras configuraciones...
[font]

normal = { family = "Hack Nerd Font Mono" , style = "Regular"}
size = 10
offset = {x = 0, y = 0}


# THEME

# # Esquema de colores Gruvbox dark
# [colors]
#   # Default colors
#   primary = { background = '0x282828', foreground = '0xebdbb2' }
#
#   # Normal colors
#   normal = { black = '0x282828', red = '0xcc241d', green = '0x98971a', yellow = '0xd79921', blue = '0x458588', magenta = '0xb16286', cyan = '0x689d6a', white = '0xa89984' }
#
#   # Bright colors
#   bright = { black = '0x928374', red = '0xfb4934', green = '0xb8bb26', yellow = '0xfabd2f', blue = '0x83a598', magenta = '0xd3869b', cyan = '0x8ec07c', white = '0xebdbb2' }


# Theme Monakai
[colors]
  # Default colors
  primary = { background = '#000000', foreground = '#FFFFFF' }

  # Normal colors
  normal = { black = '#1a1a1a', red = '#f4005f', green = '#98e024', yellow = '#fa8419', blue = '#9d65ff', magenta = '#f4005f', cyan = '#58d1eb', white = '#c4c5b5' }

  # Bright colors
  bright = { black = '#625e4c', red = '#f4005f', green = '#98e024', yellow = '#e0d561', blue = '#9d65ff', magenta = '#f4005f', cyan = '#58d1eb', white = '#f6f6ef' }
# Otras configuraciones...

